### ISSUE TITLE
run example nmt/main.py --name test throw error RuntimeError: Trying to resize storage that is not resizable at ..\aten\src\TH\THStorageFunctions.cpp:87 

### ISSUE THREAD

**Issue by over-shine** [graph4ai/graph4nlp#327]
## To Reproduce

1. run python examples/pytorch/nmt/main.py --name test

Using backend: pytorch
[ Using CUDA ]
2021-06-26 17:33:13.644323: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cudart64_110.dllLoading pre-built vocab model stored in examples/pytorch/nmt/data\processed\NodeEmbGraph\vocab.pt
2021-06-26 17:33:58,761 - examples/pytorch/nmt/log/test\txtlog.txt - INFO - ------ Running Training ----------
2021-06-26 17:33:58,762 - examples/pytorch/nmt/log/test\txtlog.txt - INFO -     Runner name: test
2021-06-26 17:33:58,763 - examples/pytorch/nmt/log/test\txtlog.txt - INFO - Start training in split train, Epoch: 0
Using backend: pytorch
RDFLib Version: 5.0.0
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Anaconda3\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Anaconda3\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "C:\Anaconda3\lib\site-packages\torch\multiprocessing\reductions.py", line 88, in rebuild_tensor
    t = torch._utils._rebuild_tensor(storage, storage_offset, size, stride)
  File "C:\Anaconda3\lib\site-packages\torch\_utils.py", line 134, in _rebuild_tensor
    return t.set_(storage, storage_offset, size, stride)
RuntimeError: Trying to resize storage that is not resizable at ..\aten\src\TH\THStorageFunctions.cpp:87

## Environment

 - Graph4NLP Version (e.g., 0.4.1): 0.4.1
 - Backend Library & Version (e.g., PyTorch 1.8.1): pytorch 1.8.1
 - OS (e.g., Linux): windows
 - How you installed Graph4NLP (`pip`, source):
 - Build command you used (if compiling from source):
 - Python version: 3.8
 - CUDA/cuDNN version: cuda 11.1
 - GPU models and configuration (Nvidia M6000):
 - Any other relevant information:

**Comment by AlanSwift** [comment]
We are trying to reproduce this bug. 
It may be caused by the spawn library. For the temporary solution, you can change this [Line](https://github.com/graph4ai/graph4nlp/blob/9e1e3b5b83362ab4d8f14b06f7d8dcccc4662cc6/examples/pytorch/nmt/main.py#L128) 's ``num_workers`` parameter to 0 (same for the validation and testing dataloaders).
Currently, we highly recommend you use the Linux platform for this initial library version since it is well tested.
