### ISSUE TITLE
Using BERT as pretrained model

### ISSUE THREAD

**Issue by icocoder** [graph4ai/graph4nlp#476]
## ❓ Questions and Help

Hello, I changed the pretrained model to 'bert' but I got the following error: 
 ```
 File "/home/hadi/miniconda3/envs/ongpu/lib/python3.9/site-packages/transformers-4.12.5-py3.9.egg/transformers/file_utils.py", line 1818, in get_list_of_files
    model_info = HfApi(endpoint=HUGGINGFACE_CO_RESOLVE_ENDPOINT).model_info(
  File "/home/hadi/miniconda3/envs/ongpu/lib/python3.9/site-packages/huggingface_hub-0.1.2-py3.9.egg/huggingface_hub/hf_api.py", line 585, in model_info
    r.raise_for_status()
  File "/home/hadi/miniconda3/envs/ongpu/lib/python3.9/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/api/models/None

```
It seems to be due to huggingface servers, but how can I fix it? 
If I want to download pretrained model manually, where should I put the file?

**Comment by icocoder** [comment]
`requests.exceptions.ConnectionError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/None (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7d01907fa0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))`

When I used a different internet connection the error changed to this, 
but I still don't know how this issue can be solved? 

I can download 'bert' manually with google colab, but where the pretrained model should  be inserted?

**Comment by hugochan** [comment]
> ## ❓ Questions and Help
> Hello, I changed the pretrained model to 'bert' but I got the following error:
> 
> ```
> File "/home/hadi/miniconda3/envs/ongpu/lib/python3.9/site-packages/transformers-4.12.5-py3.9.egg/transformers/file_utils.py", line 1818, in get_list_of_files
>    model_info = HfApi(endpoint=HUGGINGFACE_CO_RESOLVE_ENDPOINT).model_info(
>  File "/home/hadi/miniconda3/envs/ongpu/lib/python3.9/site-packages/huggingface_hub-0.1.2-py3.9.egg/huggingface_hub/hf_api.py", line 585, in model_info
>    r.raise_for_status()
>  File "/home/hadi/miniconda3/envs/ongpu/lib/python3.9/site-packages/requests/models.py", line 953, in raise_for_status
>    raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/api/models/None
> ```
> 
> It seems to be due to huggingface servers, but how can I fix it? If I want to download pretrained model manually, where should I put the file?

@icocoder Thanks for your interest to our library! Can you share more context on how you changed the pretrained model to 'bert' and what are you trying to achieve? Any code snippet for understanding/reproducing the issue will be helpful.

**Comment by icocoder** [comment]
@hugochan, I have simply changed the config file, and used different available options at [https://graph4ai.github.io/graph4nlp/guide/construction/embedding_construction.html?highlight=w2v](url).
except the ones that include 'bert', the other ones works fine. I guess the problem is that the link that is used to download 'bert' from huggingface is no longer available and needs to be changed.

**Comment by AlanSwift** [comment]
I have tested the bert and can't reproduce the error. Can you attach the more detailed error traceback? And any code snippet is helpful for us to reproduce this error.

**Comment by icocoder** [comment]
For being sure about my code, I tried the summarization example, this is the error traceback:

```
[ Using pretrained BERT embeddings ]
Traceback (most recent call last):
  File "examples/pytorch/summarization/cnn/main.py", line 436, in <module>
    main(g2s_template)
  File "examples/pytorch/summarization/cnn/main.py", line 407, in main
    runner = ModelHandler(config)
  File "examples/pytorch/summarization/cnn/main.py", line 97, in __init__
    self._build_model()
  File "examples/pytorch/summarization/cnn/main.py", line 186, in _build_model
    self.model = SumModel(self.vocab, self.config).to(self.config['device'])
  File "examples/pytorch/summarization/cnn/main.py", line 49, in __init__
    self.g2s = Graph2Seq.from_args(config, self.vocab)
  File "/usr/local/lib/python3.7/dist-packages/graph4nlp-0.4.0-py3.7.egg/graph4nlp/pytorch/models/graph2seq.py", line 204, in from_args
    return cls(vocab_model=vocab_model, **args)
  File "/usr/local/lib/python3.7/dist-packages/graph4nlp-0.4.0-py3.7.egg/graph4nlp/pytorch/models/graph2seq.py", line 67, in __init__
    **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/graph4nlp-0.4.0-py3.7.egg/graph4nlp/pytorch/models/base.py", line 37, in __init__
    emb_fix_bert_emb=emb_fix_bert_emb, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/graph4nlp-0.4.0-py3.7.egg/graph4nlp/pytorch/models/base.py", line 64, in _build_embedding_encoder
    fix_bert_emb=emb_fix_bert_emb)
  File "/usr/local/lib/python3.7/dist-packages/graph4nlp-0.4.0-py3.7.egg/graph4nlp/pytorch/modules/graph_construction/dependency_graph_construction.py", line 32, in __init__
    rnn_dropout=rnn_dropout)
  File "/usr/local/lib/python3.7/dist-packages/graph4nlp-0.4.0-py3.7.egg/graph4nlp/pytorch/modules/graph_construction/base.py", line 139, in __init__
    rnn_dropout=rnn_dropout)
  File "/usr/local/lib/python3.7/dist-packages/graph4nlp-0.4.0-py3.7.egg/graph4nlp/pytorch/modules/graph_construction/base.py", line 56, in __init__
    rnn_dropout=rnn_dropout)
  File "/usr/local/lib/python3.7/dist-packages/graph4nlp-0.4.0-py3.7.egg/graph4nlp/pytorch/modules/graph_construction/embedding_construction.py", line 185, in __init__
    lower_case=bert_lower_case)
  File "/usr/local/lib/python3.7/dist-packages/graph4nlp-0.4.0-py3.7.egg/graph4nlp/pytorch/modules/graph_construction/embedding_construction.py", line 378, in __init__
    self.bert_tokenizer = BertTokenizer.from_pretrained(name, do_lower_case=lower_case)
  File "/usr/local/lib/python3.7/dist-packages/transformers-4.15.0-py3.7.egg/transformers/tokenization_utils_base.py", line 1658, in from_pretrained
    local_files_only=local_files_only,
  File "/usr/local/lib/python3.7/dist-packages/transformers-4.15.0-py3.7.egg/transformers/tokenization_utils_base.py", line 3487, in get_fast_tokenizer_file
    path_or_repo, revision=revision, use_auth_token=use_auth_token, local_files_only=local_files_only
  File "/usr/local/lib/python3.7/dist-packages/transformers-4.15.0-py3.7.egg/transformers/file_utils.py", line 2103, in get_list_of_files
    return list_repo_files(path_or_repo, revision=revision, token=token)
  File "/usr/local/lib/python3.7/dist-packages/huggingface_hub-0.2.1-py3.7.egg/huggingface_hub/hf_api.py", line 603, in list_repo_files
    repo_id, revision=revision, token=token, timeout=timeout
  File "/usr/local/lib/python3.7/dist-packages/huggingface_hub-0.2.1-py3.7.egg/huggingface_hub/hf_api.py", line 586, in model_info
    r.raise_for_status()
  File "/usr/local/lib/python3.7/dist-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/api/models/None
```

**Comment by AlanSwift** [comment]
Can you add a breakpoint here: [https://github.com/graph4ai/graph4nlp/blob/7690b54eff4194ea0627be82a5f6316e19caddfa/graph4nlp/pytorch/modules/graph_construction/embedding_construction.py#L418](https://github.com/graph4ai/graph4nlp/blob/7690b54eff4194ea0627be82a5f6316e19caddfa/graph4nlp/pytorch/modules/graph_construction/embedding_construction.py#L418)
and print the variable value "name"?

I think you might set the wrong variable name.

**Comment by icocoder** [comment]
Yes it seems that's the problem, when I printed its name it was 'None'. 
How can fix it?

**Comment by AlanSwift** [comment]
I think you should check the config, especially the "bert_model_name" as follows:
[https://github.com/graph4ai/graph4nlp/blob/7690b54eff4194ea0627be82a5f6316e19caddfa/graph4nlp/pytorch/modules/config/graph_construction/dependency.yaml#L38](https://github.com/graph4ai/graph4nlp/blob/7690b54eff4194ea0627be82a5f6316e19caddfa/graph4nlp/pytorch/modules/config/graph_construction/dependency.yaml#L38). It should be "bert-base-uncased".


Tips: I suggest you refer to the [example code](https://github.com/graph4ai/graph4nlp/blob/7690b54eff4194ea0627be82a5f6316e19caddfa/examples/pytorch/question_generation/config/squad_split2/new_dependency_ggnn_bert.yaml). This config file is for bert based QG application. Maybe you have missed this parameter.

**Comment by icocoder** [comment]
Thank you very much, the problem is solved on the google colab. 
For the last question I wanted to ask, if I want to download 'bert' manually from huggingface, where should I put the download file so that it doesn't need to be downloaded by the framework.

**Comment by AlanSwift** [comment]
The bert weights are automatically downloaded by the API with huggingface.
[https://github.com/graph4ai/graph4nlp/blob/7690b54eff4194ea0627be82a5f6316e19caddfa/graph4nlp/pytorch/modules/graph_construction/embedding_construction.py#L419](https://github.com/graph4ai/graph4nlp/blob/7690b54eff4194ea0627be82a5f6316e19caddfa/graph4nlp/pytorch/modules/graph_construction/embedding_construction.py#L419)

You can download the weights manually and load them by:
```
self.bert_model = BertModel.from_pretrained("YOUR BERT WEIGHTS' PATH") 
```
I think you should modify this line.

**Comment by icocoder** [comment]
Thanks a lot.
