### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by nashid** [graph4ai/graph4nlp#482]
## 🐛 Bug

Graph2Seq model keeps giving `RuntimeError: CUDA out of memory`.

While training, Graph2Seq is giving the Out Of Memory (OOM) error.

## Environment

 - **Graph4NLP Version (e.g., 0.4.1)**:v0.5.1	
 - **Backend Library & Version (e.g., PyTorch 1.6.0)**: 1.10.0
 - **OS (e.g., Linux)**: CentOS
 - **How you installed Graph4NLP (`pip`, source)**: from source
 - **Build command you used (if compiling from source)**: ./configure and then python setup.py install
 - **Python version**: 3.9
 - **CUDA/cuDNN version (if applicable)**: 10.2
 - **GPU models and configuration (e.g. 2080Ti)**:V100 16GB

**Error Details:**

```
Traceback (most recent call last):

    max_score = runner.train()
      
    self.train_epoch(epoch, split="train")
  
    prob, enc_attn_weights, coverage_vectors = self.model(graph, tgt, oov_dict=oov_dict)
  File "--------------/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "--------------/lib/python3.9/site-packages/graph4nlp_cu102-0.4.0-py3.9.egg/graph4nlp/pytorch/models/graph2seq.py", line 225, in forward
    batch_graph = self.graph_topology(batch_graph)
  File "--------------/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "--------------/lib/python3.9/site-packages/graph4nlp_cu102-0.4.0-py3.9.egg/graph4nlp/pytorch/modules/graph_construction/node_embedding_based_graph_construction.py", line 46, in forward
    batch_graphdata = self.topology(batch_graphdata)
  File "--------------/lib/python3.9/site-packages/graph4nlp_cu102-0.4.0-py3.9.egg/graph4nlp/pytorch/modules/graph_construction/node_embedding_based_graph_construction.py", line 67, in topology
    raw_adj = self.sparsify_graph(raw_adj)
  File "--------------/lib/python3.9/site-packages/graph4nlp_cu102-0.4.0-py3.9.egg/graph4nlp/pytorch/modules/graph_construction/base.py", line 425, in sparsify_graph
    adj = self._build_epsilon_neighbourhood(adj, self.epsilon_neigh)
  File "--------------/lib/python3.9/site-packages/graph4nlp_cu102-0.4.0-py3.9.egg/graph4nlp/pytorch/modules/graph_construction/base.py", line 519, in _build_epsilon_neighbourhood
    weighted_adj = attention * mask + self.mask_off_val * (1 - mask)
  File "--------------/lib/python3.9/site-packages/torch/_tensor.py", line 30, in wrapped
    return f(*args, **kwargs)
  File "--------------/lib/python3.9/site-packages/torch/_tensor.py", line 548, in __rsub__
    return _C._VariableFunctions.rsub(self, other)
RuntimeError: CUDA out of memory. Tried to allocate 3.37 GiB (GPU 0; 15.78 GiB total capacity; 12.16 GiB already allocated; 1.87 GiB free; 12.39 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```
## Questions? - How to mitigate this error?

I presume if I use a smaller batch size, this error would be resolved? Please let me know what other steps could be taken.

**Comment by AlanSwift** [comment]
Yes, try a small batch_size or use gpus with larger memory.

**Comment by AlanSwift** [comment]
Closed.
