### ISSUE TITLE
IndexError while doing inference with top_k > 1

### ISSUE THREAD

**Issue by nashid** [graph4ai/graph4nlp#504]
## 🐛 Bug

Graph2Seq model is giving `IndexError` during inference stage when top_k > 1.:

```
Traceback (most recent call last):
  File "/xxxxx", line 241, in <module>
    runner.translate()
  File "/xxxx/python3.9/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/xxxx", line 188, in translate
    pred = self.model.translate(
  File "/xxxx/python3.9/site-packages/graph4nlp_cu111-0.4.0-py3.9.egg/graph4nlp/pytorch/models/graph2seq.py", line 251, in translate
    return self.encoder_decoder_beam_search(
  File "/xxxx/python3.9/site-packages/graph4nlp_cu111-0.4.0-py3.9.egg/graph4nlp/pytorch/models/graph2seq.py", line 198, in encoder_decoder_beam_search
    beam_results = generator.generate(batch_graph=batch_graph, oov_dict=oov_dict, topk=topk)
  File "/xxxx/python3.9/site-packages/graph4nlp_cu111-0.4.0-py3.9.egg/graph4nlp/pytorch/modules/prediction/generation/decoder_strategy.py", line 150, in generate
    return self._beam_search(**params)
  File "/xxxx/lib/python3.9/site-packages/graph4nlp_cu111-0.4.0-py3.9.egg/graph4nlp/pytorch/modules/prediction/generation/decoder_strategy.py", line 378, in _beam_search
    ids = torch.Tensor(each[i].tokens[1:])[: self.max_decoder_step]
IndexError: list index out of range
```

It is happening when top_k > 1.
```
top_k = 5
beam_size = 20
pred = self.model.translate(
                batch_graph=batch_graph, oov_dict=oov_dict, beam_size=beam_size, topk=top_k
            )
```

## Expected behavior

Inference with top-k should produce top-k inferences.

**Comment by nashid** [comment]
Inference works:

```
top_k = 1
beam_size = 5
```

Then when I set:
```
top_k = 5
beam_size = 5
```
Inference fails with:

```
  File "xxxx/lib/python3.9/site-packages/graph4nlp_cu111-0.4.0-py3.9.egg/graph4nlp/pytorch/modules/prediction/generation/decoder_strategy.py", line 378, in _beam_search
    ids = torch.Tensor(each[i].tokens[1:])[: self.max_decoder_step]
IndexError: list index out of range
```

Can anyone please provide me with any pointers here?

**Comment by AlanSwift** [comment]
Thanks for your feedback and I will figure it out.

**Comment by nashid** [comment]
@AlanSwift thanks a lot for looking into the issue. Wondering when can we expect the bug-fix?

**Comment by nashid** [comment]
@AlanSwift sorry for pinging you again on this. I also see https://github.com/graph4ai/graph4nlp/issues/505 which mentions issues with beam search.

I am wondering when this issue will be resolved?

**Comment by nashid** [comment]
@AlanSwift sorry for asking again. Wondering when do we think this issue would be resolved? Would really appreciate your help.

**Comment by AlanSwift** [comment]
I can't reproduce it. Can you attach your environments according to the guidance in the [issue template](https://github.com/graph4ai/graph4nlp/issues/new?assignees=&labels=&template=bug-report.md)? (I have tested it and it works fine.)

**Comment by nashid** [comment]
@AlanSwift thanks for looking into it. Really appreciate it. This is the code snippet I used:

```
            top_k = 5
            beam_size = 5
   
            pred = self.model.translate(
                batch_graph=batch_graph, oov_dict=oov_dict, beam_size=beam_size, topk=top_k
            )

            pred_strs = []
            pred_collect_top_k = []
            for i in range(top_k):
                pred_ids = pred[:, i, :]
                pred_str = wordid2str(pred_ids.detach().cpu(), ref_dict)
                pred_strs.extend(pred_str)
                pred_collect_top_k.extend(pred_str)
```

Am I missing something here? Would you point me to the code snippet that you have used?

**Comment by AlanSwift** [comment]
I still can't reproduce it.
You can try this branch: [NMT](https://github.com/graph4ai/graph4nlp/tree/bug-beam_search_topk).
For training:
```
python examples/pytorch/nmt/main.py --name test
```
For inference: beam=5, top_k=5, see [inference_advance.py](https://github.com/graph4ai/graph4nlp/blob/0657b812982be0f9672b4baae7ec0822680d1ba0/examples/pytorch/nmt/inference_advance.py#L119)
```
python examples/pytorch/nmt/inference_advance.py --name test
```
The outputs are correct.
