### ISSUE TITLE
GAT with copy mechanism gives error token_id_oov doesn't exist

### ISSUE THREAD

**Issue by nashid** [graph4ai/graph4nlp#524]
## 🐛 Bug

GAT with copy mechanism gives the error `Node feature token_id_oov doesn't exist`.

```
Traceback (most recent call last):
    prob, enc_attn_weights, coverage_vectors = self.model(graph, tgt, oov_dict=oov_dict)
  File "/mnt/volume1/anaconda3/envs/gat/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/volume1/anaconda3/envs/gat/lib/python3.9/site-packages/graph4nlp_cu111-0.4.0-py3.9.egg/graph4nlp/pytorch/models/graph2seq.py", line 226, in forward
    return self.encoder_decoder(batch_graph=batch_graph, oov_dict=oov_dict, tgt_seq=tgt_seq)
  File "/mnt/volume1/anaconda3/envs/gat/lib/python3.9/site-packages/graph4nlp_cu111-0.4.0-py3.9.egg/graph4nlp/pytorch/models/graph2seq.py", line 177, in encoder_decoder
    prob, enc_attn_weights, coverage_vectors = self.seq_decoder(
  File "/mnt/volume1/anaconda3/envs/gat/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/volume1/anaconda3/envs/gat/lib/python3.9/site-packages/graph4nlp_cu111-0.4.0-py3.9.egg/graph4nlp/pytorch/modules/prediction/generation/StdRNNDecoder.py", line 572, in forward
    params = self.extract_params(batch_graph)
  File "/mnt/volume1/anaconda3/envs/gat/lib/python3.9/site-packages/graph4nlp_cu111-0.4.0-py3.9.egg/graph4nlp/pytorch/modules/prediction/generation/StdRNNDecoder.py", line 602, in extract_params
    src_seq_ret = batch_graph.batch_node_features["token_id_oov"]
  File "/mnt/volume1/anaconda3/envs/gat/lib/python3.9/site-packages/graph4nlp_cu111-0.4.0-py3.9.egg/graph4nlp/pytorch/data/views.py", line 147, in __getitem__
    return self._graph._get_batch_node_features(item)
  File "/mnt/volume1/anaconda3/envs/gat/lib/python3.9/site-packages/graph4nlp_cu111-0.4.0-py3.9.egg/graph4nlp/pytorch/data/data.py", line 939, in _get_batch_node_features
    raise Exception("Node feature {} doesn't exist!".format(item))
Exception: Node feature token_id_oov doesn't exist!
```

**Comment by hugochan** [comment]
@nashid thanking you for reporting the error! Can you share more context to help us reproduce the error? Are you running one of the provided example applications or building your own application? Did you observe this error with other GNN variants besides GAT?

**Comment by nashid** [comment]
@hugochan I am running the provided example of the `NMT` but I enabled the copy mechanism as my source and target vocabulary is the same. 

Currently [`oov_dict = None`](https://github.com/nashid/Slice4Context/blob/main/graph2seq-gnn-variants/ast_main_gat.py#L230)

Looks like I have to use the API `prepare_ext_vocab`. Probably something like:

```
            oov_dict = prepare_ext_vocab(
                batch_graph=graph, vocab=self.vocab, device=self.device
            )
```

Please correct me if I am wrong.
