### ISSUE TITLE
How to incorporate different pre-trained models?

### ISSUE THREAD

**Issue by code-rex1** [graph4ai/graph4nlp#534]
## ❓ Questions and Help

I want to use different pre-trained model. Lets say I want to use [CodeBERT](https://huggingface.co/microsoft/codebert-base) pre-trained embedding.

Is the framework extendable to use different pre-trained embedding? Or it is not possible? Any pointers welcome.

**Comment by nashid** [comment]
@code-rex1 I dont pretend to be expert here. But looks like you can set the `bert_model_name` in the config file and that should do.

https://github.com/graph4ai/graph4nlp/blob/7690b54eff4194ea0627be82a5f6316e19caddfa/graph4nlp/pytorch/modules/config/graph_construction/dependency.yaml#L38

**Comment by AlanSwift** [comment]
Yes. Thanks a lot! @nashid

**Comment by code-rex1** [comment]
@nashid The solution provided by you does not work:

```
  node_embedding:
    input_size: 300
    hidden_size: 300
    word_dropout: 0.2
    rnn_dropout: 0.3
    fix_bert_emb: false
    fix_word_emb: false
    embedding_style:
      single_token_item: true
      emb_strategy: "w2v_bert_bilstm"
      num_rnn_layers: 2
      bert_model_name: "microsoft/codebert-base"
      bert_lower_case: true
```

Error:
```
The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'RobertaTokenizer'. 
The class this function is called from is 'BertTokenizer'.
Traceback (most recent call last):
    runner = NMT(opt)
    self._build_model()
    self.model = get_model(self.opt, vocab_model=self.vocab, device=self.device).to(self.device)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/nmt-graph4nlp-env-custom/lib/python3.9/site-packages/graph4nlp-0.4.0-py3.9.egg/graph4nlp/pytorch/models/graph2seq.py", line 280, in from_args
    return cls(vocab_model=vocab_model, **args)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/nmt-graph4nlp-env-custom/lib/python3.9/site-packages/graph4nlp-0.4.0-py3.9.egg/graph4nlp/pytorch/models/graph2seq.py", line 76, in __init__
    super(Graph2Seq, self).__init__(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/nmt-graph4nlp-env-custom/lib/python3.9/site-packages/graph4nlp-0.4.0-py3.9.egg/graph4nlp/pytorch/models/base.py", line 53, in __init__
    self._build_embedding_encoder(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/nmt-graph4nlp-env-custom/lib/python3.9/site-packages/graph4nlp-0.4.0-py3.9.egg/graph4nlp/pytorch/models/base.py", line 133, in _build_embedding_encoder
    self.graph_topology = NodeEmbeddingBasedGraphConstruction(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/nmt-graph4nlp-env-custom/lib/python3.9/site-packages/graph4nlp-0.4.0-py3.9.egg/graph4nlp/pytorch/modules/graph_construction/node_embedding_based_graph_construction.py", line 28, in __init__
    super(NodeEmbeddingBasedGraphConstruction, self).__init__(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/nmt-graph4nlp-env-custom/lib/python3.9/site-packages/graph4nlp-0.4.0-py3.9.egg/graph4nlp/pytorch/modules/graph_construction/base.py", line 252, in __init__
    super(DynamicGraphConstructionBase, self).__init__(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/nmt-graph4nlp-env-custom/lib/python3.9/site-packages/graph4nlp-0.4.0-py3.9.egg/graph4nlp/pytorch/modules/graph_construction/base.py", line 49, in __init__
    self.embedding_layer = EmbeddingConstruction(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/nmt-graph4nlp-env-custom/lib/python3.9/site-packages/graph4nlp-0.4.0-py3.9.egg/graph4nlp/pytorch/modules/graph_construction/embedding_construction.py", line 194, in __init__
    self.word_emb_layers["seq_bert"] = BertEmbedding(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/nmt-graph4nlp-env-custom/lib/python3.9/site-packages/graph4nlp-0.4.0-py3.9.egg/graph4nlp/pytorch/modules/graph_construction/embedding_construction.py", line 418, in __init__
    self.bert_tokenizer = BertTokenizer.from_pretrained(name, do_lower_case=lower_case)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/nmt-graph4nlp-env-custom/lib/python3.9/site-packages/transformers-4.12.5-py3.9.egg/transformers/tokenization_utils_base.py", line 1744, in from_pretrained
    return cls._from_pretrained(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/nmt-graph4nlp-env-custom/lib/python3.9/site-packages/transformers-4.12.5-py3.9.egg/transformers/tokenization_utils_base.py", line 1872, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/nmt-graph4nlp-env-custom/lib/python3.9/site-packages/transformers-4.12.5-py3.9.egg/transformers/models/bert/tokenization_bert.py", line 193, in __init__
    if not os.path.isfile(vocab_file):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/nmt-graph4nlp-env-custom/lib/python3.9/genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

@AlanSwift the solution provided by @nashid does not work. Can you please provide any pointers?

**Comment by code-rex1** [comment]
@AlanSwift the solution suggested about does not work and I get `TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType`.

Can you please help?

**Comment by hugochan** [comment]
@code-rex1 currently, only BERT model is supported ([code](https://github.com/graph4ai/graph4nlp/blob/master/graph4nlp/pytorch/modules/graph_embedding_initialization/embedding_construction.py#L414)). We will definitely consider supporting more pre-trained language models in the future. Please stay tuned.

**Comment by code-rex1** [comment]
@hugochan looking forward to it. I have to try out the [CodeBERT](https://huggingface.co/microsoft/codebert-base) pre-trained embedding urgently 😓 

Would you mind providing me with some pointers so that I can give a go 🙏

**Comment by nashid** [comment]
@code-rex1 I presume you can try with [Auto Classes](https://huggingface.co/docs/transformers/model_doc/auto). [Auto Classes](https://huggingface.co/docs/transformers/model_doc/auto) will select the proper classes for you:

```
from transformers import AutoTokenizer, AutoModel

name = "microsoft/codebert-base"
tokenizer = AutoTokenizer.from_pretrained(name)
model = AutoModel.from_pretrained(name)
```

I presume that's all you need. But of course, I am no expert here. @hugochan and @AlanSwift can suggest you much better.

**Comment by code-rex1** [comment]
> ```
> from transformers import AutoTokenizer, AutoModel
> 
> name = "microsoft/codebert-base"
> tokenizer = AutoTokenizer.from_pretrained(name)
> model = AutoModel.from_pretrained(name)
> ```

Will this solution suggested above would work @hugochan @AlanSwift? Please help 🙏

**Comment by hugochan** [comment]
> > ```
> > from transformers import AutoTokenizer, AutoModel
> > 
> > name = "microsoft/codebert-base"
> > tokenizer = AutoTokenizer.from_pretrained(name)
> > model = AutoModel.from_pretrained(name)
> > ```
> 
> 
> Will this solution suggested above would work @hugochan @AlanSwift? Please help 🙏

@code-rex1 I am not familiar with `AutoModel`, but after a quick review on HuggingFace Auto Classes, this sounds to me a promising solution to supporting various pre-trained models in a unified way in our library. We will definitely consider this solution when we work on supporting more pre-trained language models in the future. 

As of now, you will need to build your own customized embedding class following this [example](https://github.com/graph4ai/graph4nlp/blob/master/graph4nlp/pytorch/modules/graph_embedding_initialization/embedding_construction.py#L383). Please also feel free to submit a PR if you want to contribute to the library regarding this effort.
